fast = DoyouknowKorean?
fast-reply = Please say it again.
fast-reply-intent = Ask him to repeat it
fast-alt1 = Hello.
fast-alt1-intent = Greet him again
fast-alt1-answer = Hello. Do you know Korean?
fast-alt2 = Goodbye.
fast-alt2-intent = See him off
fast-alt2-answer = Do you know Korean?

again = DoyouknowKorean? Slowly?
again-reply = Please say it slowly. Thank you.
again-reply-intent = Ask for a slower repeat and thank him
again-alt1 = Please tell me.
again-alt1-intent = Ask him to speak without saying how
again-alt1-answer = Slowly?
again-alt2 = Are you Grandpa Park?
again-alt2-intent = Check his name again
again-alt2-answer = I'm Grandpa Park. Slowly.

slow = OK. Korean… do you know it?
slow-reply = No, I don't know it.
slow-reply-intent = Answer his question honestly
slow-alt1 = It's a newspaper.
slow-alt1-intent = Name his newspaper
slow-alt1-answer = A newspaper? Do you know Korean?
slow-alt2 = Goodbye.
slow-alt2-intent = See him off
slow-alt2-answer = Do you know Korean?
