hello = Hello.
hello-reply = Hello.
hello-reply-intent = Say hello
hello-alt1 = Goodbye (go well).
hello-alt1-intent = See him off
hello-alt1-answer = Goodbye? Hello!
hello-alt2 = Goodbye (stay well).
hello-alt2-intent = Say goodbye as you leave
hello-alt2-answer = Hello!

park = I'm Grandpa Park.
park-reply = Hello, Grandpa Park.
park-reply-intent = Greet him by name
park-alt1 = Goodbye, Grandpa Park.
park-alt1-intent = See him off
park-alt1-answer = I'm Grandpa Park. Hello!
park-alt2 = Min-jun?
park-alt2-intent = Offer the name on the card
park-alt2-answer = I'm Grandpa Park.

ask = Min-jun? Please tell me.
ask-reply = No. I'm { $player }.
ask-reply-intent = Correct him with your own name
ask-alt1 = I'm Min-jun.
ask-alt1-intent = Use the name on the ID card
ask-alt1-answer = Min-jun?
ask-alt2 = I'm Min-jun's friend.
ask-alt2-intent = Say you're Min-jun's friend
ask-alt2-answer = A friend? Please tell me.

newspaper = Is it a newspaper?
newspaper-reply = Yes, it's a newspaper.
newspaper-reply-intent = Confirm the desk word
newspaper-alt1 = Goodbye.
newspaper-alt1-intent = See him off
newspaper-alt1-answer = It's a newspaper!
newspaper-alt2 = Are you Grandpa Park?
newspaper-alt2-intent = Check his name again
newspaper-alt2-answer = I'm Grandpa Park. It's a newspaper.
