import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { PackMeta, PackWord, VocabPackJson, VocabWordJson } from "./pack";

/** Fluent-escapes a single-line value: braces must be written as string literals. */
export function ftlValue(s: string): string {
  const flat = s.replace(/\s+/g, " ").trim();
  if (!flat) return '{""}';
  return flat.replace(/[{}]/g, (c) => `{"${c}"}`);
}

export interface ImportResult {
  meta: PackMeta;
  words: PackWord[];
  glossesFtl: string;
}

/** Word ids become Fluent message ids, so they must be valid ones. */
const FTL_ID = /^[a-zA-Z][a-zA-Z0-9_-]*$/;

/** Every problem in the input, so one run reports them all. */
export function packProblems(pack: VocabPackJson, words: VocabWordJson[], existing?: PackMeta): string[] {
  const levels = new Set(pack.levels.map((l) => String(l.id)));
  const problems: string[] = [];
  const seen = new Set<string>();
  for (const [i, v] of words.entries()) {
    const at = `word ${i} (${v.id ?? "no id"})`;
    if (typeof v.id !== "string" || !FTL_ID.test(v.id)) problems.push(`${at}: id must match ${FTL_ID}`);
    else if (seen.has(v.id)) problems.push(`${at}: duplicate id`);
    else seen.add(v.id);
    if (typeof v.w !== "string" || !v.w) problems.push(`${at}: missing w`);
    if (typeof v.en !== "string") problems.push(`${at}: missing en`);
    if (!levels.has(String(v.lv))) problems.push(`${at}: level "${v.lv}" is not in the pack's levels`);
  }
  for (const [stage, lvs] of Object.entries(existing?.stages ?? {})) {
    for (const lv of lvs) if (!levels.has(lv)) problems.push(`stage ${stage}: level "${lv}" is not in the pack's levels`);
  }
  return problems;
}

/**
 * Converts a vocab-engine pack. `existing` is our current pack.json, whose
 * hand-set fields (stages) survive a re-import. Throws on bad input, listing every problem.
 */
export function convertPack(pack: VocabPackJson, words: VocabWordJson[], existing?: PackMeta): ImportResult {
  const problems = packProblems(pack, words, existing);
  if (problems.length) throw new Error(`vocab-engine pack "${pack.key}" can't be imported:\n  ${problems.join("\n  ")}`);
  const levels = pack.levels.map((l) => String(l.id));
  const meta: PackMeta = {
    key: pack.key,
    name: pack.name,
    locale: pack.langTag ?? pack.tts.split("-")[0],
    tts: pack.tts,
    ...(pack.ttsRate !== undefined && { ttsRate: pack.ttsRate }),
    levels,
    stages: existing?.stages ?? Object.fromEntries(levels.map((lv, i) => [String(i + 1), [lv]])),
    typing: pack.typing ?? null,
    spaced: pack.spaced !== false,
  };
  const out: PackWord[] = words.map((v) => {
    const w: PackWord = { id: v.id, w: v.w, lv: String(v.lv) };
    if (v.alt?.length) w.alt = v.alt;
    if (v.pron) w.pron = v.pron;
    if (v.pos) w.pos = v.pos;
    return w;
  });
  const glossesFtl =
    `# Generated by tools/src/import-vocab-pack.ts from vocab-engine pack "${pack.key}". Do not edit.\n` +
    words.map((v) => `${v.id} = ${ftlValue(v.en)}`).join("\n") +
    "\n";
  return { meta, words: out, glossesFtl };
}

function main(): void {
  const [src, outDir, glossesPath] = process.argv.slice(2);
  if (!src || !outDir || !glossesPath) {
    console.error("usage: import-vocab-pack <vocab-pack-dir> <out-language-dir> <out-glosses.ftl>");
    process.exit(2);
  }
  const pack = JSON.parse(readFileSync(join(src, "pack.json"), "utf8")) as VocabPackJson;
  const words = JSON.parse(readFileSync(join(src, "words.json"), "utf8")) as VocabWordJson[];
  const metaPath = join(outDir, "pack.json");
  const existing = existsSync(metaPath) ? (JSON.parse(readFileSync(metaPath, "utf8")) as PackMeta) : undefined;
  const res = convertPack(pack, words, existing);
  mkdirSync(outDir, { recursive: true });
  mkdirSync(dirname(glossesPath), { recursive: true });
  writeFileSync(metaPath, JSON.stringify(res.meta, null, 2) + "\n");
  writeFileSync(join(outDir, "words.json"), JSON.stringify(res.words, null, 1) + "\n");
  writeFileSync(glossesPath, res.glossesFtl);
  console.log(`imported ${res.words.length} words into ${outDir}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
