# Hand-written glosses for content/languages/ko/words.json and extra-words.json, in the sense the scenes use.
ko-ssi = Mr; Ms (after a name, polite)
ko-ne = yes; yes?
ko-chingu = friend
ko-ieyo = is; am; are (polite, after a noun)
ko-aniyo = no
ko-yeogi = here
ko-bang = room
ko-nugu = who
ko-jeo = I; me (humble)
ko-neun = (topic marker: "as for …", after a vowel)
ko-eun = (topic marker: "as for …", after a consonant)
ko-annyeonghi = in peace; well
ko-gyeseyo = stay (polite: 안녕히 계세요, "goodbye" to someone staying)
ko-gayo = to go (polite: 안녕히 가세요, "goodbye" to someone leaving)
ko-annyeonghaseyo = hello
ko-harabeoji = grandfather; old man (polite address)
ko-ireum = name
ko-i = (subject marker, after a consonant)
ko-ga = (subject marker, after a vowel)
ko-mwo = what
ko-anjayo = to sit (polite)
ko-gamsahamnida = thank you
ko-hangugeo = Korean (the language)
ko-arayo = to know
ko-mollayo = don't know
ko-hana = one (native Korean)
ko-dul = two (native Korean)
ko-set = three (native Korean)
ko-net = four (native Korean)
ko-daseot = five (native Korean)
ko-baegopayo = to be hungry
ko-don = money
ko-isseoyo = there is; to have
ko-eopseoyo = there isn't; to not have
ko-jeogi = over there
ko-bunsikjip = snack stall; cheap eatery
ko-eoseo = quickly; please (come in)
ko-wayo = to come (polite: 어서 오세요, "welcome")
ko-gwaenchanayo = it's fine; it's all right
ko-meogeoyo = to eat
ko-tteokbokki = tteokbokki (spicy rice cakes)
ko-gimbap = gimbap (rice rolled in seaweed)
ko-do = too; also (after a noun)
ko-eomuk = fish cake
ko-ilhaeyo = to work
ko-gachi = together
ko-juseyo = please give; … please
ko-gae = (counter for things)
ko-geureut = bowl (counter for bowls)
ko-jul = roll; line (counter for gimbap)
ko-myeot = how many
ko-igeo = this; this thing
ko-bwayo = to look; to see
ko-sajin = photo
ko-dongsaeng = younger brother or sister
ko-jigeum = now
ko-bangse = rent (for a room)
ko-naeyo = to pay
ko-o = five (Sino-Korean, for prices and dates)
ko-man = ten thousand
ko-won = won (money)
ko-iljuil = one week
ko-e = at; in; per
ko-sam = three (Sino-Korean, for prices and dates)
ko-wol = month (삼월, "March")
ko-kkaji = until; up to
ko-uyu = milk
ko-cheon = thousand
ko-ppang = bread
ko-reul = (object marker, after a vowel)
ko-eul = (object marker, after a consonant)
ko-eodi = where
ko-dasi = again
ko-malhaeyo = to speak; to say (polite: 말해 주세요, "please say it")
ko-cheoncheonhi = slowly
ko-chaek = book
ko-joayo = good; to be good
ko-sinmun = newspaper
ko-jeogeo = that (thing over there)
ko-gage = shop
ko-eolma = how much
ko-masisseoyo = tasty; delicious
ko-sa = four (Sino-Korean, for prices and dates)
ko-mianhaeyo = sorry
