# Hand-written glosses for content/languages/ja/words.json and extra-words.json, in the sense the scenes use.
ja-konnichiwa = hello; good afternoon
ja-desu = is; am; are (polite)
ja-san = Mr; Ms (after a name)
ja-dozo = please; go ahead; here you are
ja-arigatogozaimasu = thank you (polite)
ja-sayonara = goodbye
ja-chigaimasu = that's wrong; it's different
ja-ikutsu = how many
ja-ka = (question marker, at the end of a sentence)
ja-ocha = tea (green tea)
ja-mizu = water
ja-onigiri = rice ball
ja-pan = bread
ja-num1 = one
ja-num2 = two
ja-num3 = three
ja-num4 = four
ja-num5 = five
ja-tanaka = Tanaka (a family name)
ja-namae = name
ja-wa = (topic marker: "as for …")
ja-watashi = I; me
ja-yoroshiku = nice to meet you; please treat me well
ja-nihongo = Japanese (the language)
ja-wakarimasu = to understand
ja-iie = no
ja-ja = well then
ja-mata = again; see you
ja-hai = yes
ja-koko = here; this place
ja-no = (of; 's: joins two nouns)
ja-heya = room
ja-kore = this; this one
ja-kagi = key
ja-oyasuminasai = good night
ja-maishu = every week
ja-sen = thousand
ja-en = yen
ja-okane = money
ja-ga = (subject marker)
ja-arimasu = to have; there is (for things)
ja-ramenya = ramen shop
ja-de = at; in (where something happens)
ja-hatarakimasu = to work
ja-ooya = landlord; landlady
ja-yachin = rent
ja-irasshaimase = welcome (said to customers)
ja-ramen = ramen (noodle soup)
ja-tabemasu = to eat
ja-ne = (isn't it; right: at the end of a sentence)
ja-ashita = tomorrow
ja-o = (object marker)
ja-kudasai = please (give me)
ja-hyaku = hundred
ja-ju = ten
ja-mo = also; too
ja-sore = that; that one (near you)
ja-yo = (you know: at the end of a sentence, telling something)
ja-kyo = today
ja-ame = rain
ja-furimasu = to fall (rain, snow)
ja-samui = cold (weather)
ja-kasa = umbrella
ja-oishii = tasty; delicious
ja-takai = expensive; tall
ja-yasui = cheap
ja-nomimasu = to drink
ja-ohayogozaimasu = good morning (also the greeting at the start of a shift)
ja-shigoto = work; job
ja-ji = o'clock
ja-kara = from
ja-made = until; as far as
ja-mainichi = every day
ja-nani = what
ja-kaimasu = to buy
ja-to = and (joins two nouns)
ja-jaarimasen = is not (polite)
ja-sumimasen = excuse me; sorry
ja-kimasu = to come
ja-he = to; toward (said e)
ja-ikimasu = to go
ja-konbini = convenience store
ja-issho = together
ja-ni = (to; at; in: where, when, or the person)
ja-kaerimasu = to go home; to return
ja-doko = where
