# Hand-written glosses for content/languages/ja/words.json and extra-words.json, in the sense the scenes use.
ja-konnichiwa = hello; good afternoon
ja-desu = is; am; are (polite)
ja-san = Mr; Ms (after a name)
ja-dozo = please; go ahead; here you are
ja-arigatogozaimasu = thank you (polite)
ja-sayonara = goodbye
ja-chigaimasu = that's wrong; it's different
ja-ikutsu = how many
ja-ka = (question marker, at the end of a sentence)
ja-ocha = tea (green tea)
ja-mizu = water
ja-onigiri = rice ball
ja-pan = bread
ja-num1 = one
ja-num2 = two
ja-num3 = three
ja-num4 = four
ja-num5 = five
ja-tanaka = Tanaka (a family name)
ja-namae = name
ja-wa = (topic marker: "as for …")
ja-watashi = I; me
ja-yoroshiku = nice to meet you; please treat me well
ja-nihongo = Japanese (the language)
ja-wakarimasu = to understand
ja-iie = no
ja-ja = well then
ja-mata = again; see you
ja-hai = yes
ja-koko = here; this place
ja-no = (of; 's: joins two nouns)
ja-heya = room
ja-kore = this; this one
ja-kagi = key
ja-oyasuminasai = good night
ja-maishu = every week
ja-sen = thousand
ja-en = yen
ja-okane = money
ja-ga = (subject marker)
ja-arimasu = to have; there is (for things)
ja-ramenya = ramen shop
ja-de = at; in (where something happens)
ja-hatarakimasu = to work
ja-ooya = landlord; landlady
ja-yachin = rent
