# The story. intro-1, intro-2, … open a new game ($currency, $wallet, $rent are available).
intro-1 = Your phone is dead, your wallet is gone, and the bus that brought you here left an hour ago.
intro-2 = You're standing on a street in a Chinese city with { $currency }{ $wallet } in your pocket. You know nobody, and nobody here speaks your language.
intro-3 = Food costs money. There's a room for you down the street, and the rent, { $currency }{ $rent }, is due at the end of each week. To earn anything you'll need work, and for work you'll need words.
intro-4 = On a bench by the road, an old man is watching you with open curiosity. Maybe start there.

place-street = Main Street
place-street-desc = Bikes, steam and shouting. An old man sits on a bench by the road. Across it, a noodle shop glows, and past it the street opens onto Market Street, where your room is.
place-noodle_shop = Noodle Shop
place-noodle_shop-desc = Steam everywhere. The cook is shouting orders at nobody in particular.
place-room = Your Room
place-room-desc = A narrow bed and a window onto the street. The landlord seems to hear every step on the stairs.
place-market = Market Street
place-market-desc = Stalls, scooters and a warehouse with its doors wide open. A young woman sits behind a stall piled with parcels. Your room is up the stairs above a shuttered shop, and at the far end the road runs down to the station.
place-station_road = Station Road
place-station_road-desc = A wide road down to the train station. The school is in front of the hospital, the station is behind it, and a tea house steams on the corner.
place-school = School
place-school-desc = Children's voices through the open windows, and a teacher at the gate.
place-hospital = Hospital
place-hospital-desc = White walls and a long queue. A doctor hurries past.
place-station = Train Station
place-station-desc = Announcements you can't follow, people with too much luggage, and a taxi driver shouting for fares.
place-shop = Corner Shop
place-shop-desc = Shelves to the ceiling, a crate of apples by the door, and a shopkeeper who misses nothing.
place-warehouse = Warehouse
place-warehouse-desc = Stacks of tables and chairs, and a big man with a clipboard.

npc-wang = Old Wang
npc-cook = Cook
npc-landlord = Mr Li
npc-foreman = Big Liu
npc-dispatcher = Miss Gao
npc-doctor = Doctor
npc-teacher = Teacher
npc-traveller = Traveller
npc-shopkeeper = Shopkeeper

# Scene names for the menu; scene-<id>-start and scene-<id>-end are optional narration.
scene-street-hello = Meet Old Wang
scene-street-hello-start = The old man pats the bench beside him and points at himself. He seems to have decided you need lessons: he says something, you answer. Stuck? Press [w] to look words up, and [s] there to see what the whole sentence means.
scene-street-hello-end = Old Wang looks delighted with his new student. He repeats your name a few times, getting it a little wrong each time, and seems very pleased about it.

scene-street-hungry = Talk about food
scene-street-hungry-start = Your stomach growls, loudly. Old Wang raises an eyebrow.
scene-street-hungry-end = Old Wang points at the noodle shop, then at you, then holds up his fingers one by one. Work first, noodles after, and counting before either.

scene-street-practice = Practise greetings
scene-street-practice-start = Old Wang shuffles over to make room. Another lesson, then.
scene-street-practice-end = Old Wang nods, satisfied, and goes back to watching the street.

scene-street-numbers = Count with Old Wang
scene-street-numbers-start = Old Wang holds up one finger, then another. Anyone who works at the noodle shop has to count, and he means to make sure you can.
scene-street-numbers-end = Old Wang makes you count on your own fingers, twice, just to be sure. Now the noodle shop.

scene-noodle-intro = Ask about work
scene-noodle-intro-start = The cook looks you up and down, wiping her hands on her apron. So this is Old Wang's latest project.
scene-noodle-intro-end = She throws you an apron. You have a job, sort of.

scene-noodle-shift = Work a shift
scene-noodle-shift-start = Orders fly across the counter. Keep up.
scene-noodle-shift-end = The rush dies down. The cook counts coins into your hand.

scene-room-hello = Meet the landlord
scene-room-hello-start = A thin man in slippers opens the door before you knock. He has clearly been expecting you.
scene-room-hello-end = Mr Li hands you a key on a red string, and points firmly at the bed. You'll sleep here.
scene-room-rent = Talk about rent
scene-room-rent-start = Mr Li is waiting at the top of the stairs. He rubs his thumb and fingers together, politely.
scene-room-rent-end = Mr Li nods and writes it on the back of his hand: fifty, every week. It'll come out of your pocket at the end of the week either way.

scene-warehouse-intro = Meet the foreman
scene-warehouse-intro-start = The big man with the clipboard looks up. He holds up five fingers, then all ten, and raises an eyebrow: can you count that far?
scene-warehouse-intro-end = Big Liu writes something on his clipboard, possibly your name. There's work here whenever you want it.

scene-warehouse-shift = Carry furniture
scene-warehouse-shift-start = A truck backs up to the doors. Big Liu reads from his clipboard; you do the lifting.
scene-warehouse-shift-end = The truck pulls away. Big Liu counts out your pay, twice.

scene-delivery-intro = Meet Miss Gao
scene-delivery-intro-start = A young woman at a stall piled with parcels waves you over. She points down the road, and starts naming things.
scene-delivery-intro-end = Miss Gao writes your name on a parcel label, then holds the parcel out to you.
scene-delivery-pickup = Take a delivery
scene-delivery-pickup-start = Miss Gao lifts a parcel onto the counter and taps the label.
scene-delivery-pickup-end = You tuck the parcel under your arm. Now, where was it going?
scene-delivery-hospital = Deliver the parcel
scene-delivery-hospital-start = A doctor in a white coat looks at the parcel under your arm.
scene-delivery-hospital-end = The doctor signs for the parcel and pays you.
scene-delivery-school = Deliver the parcel
scene-delivery-school-start = The teacher at the gate looks at the parcel under your arm.
scene-delivery-school-end = The teacher carries the parcel inside, and pays you.
scene-delivery-station = Deliver the parcel
scene-delivery-station-start = A traveller sitting on a suitcase jumps up when she sees the parcel.
scene-delivery-station-end = She takes the parcel, pays you, and runs for her train.

scene-noodle-kitchen = Wash dishes
scene-noodle-kitchen-start = The sink is full, and the cook needs clean cups faster than you can wash them.
scene-noodle-kitchen-end = The last cup is dry, and the cook pays you.
scene-shop-intro = Meet the shopkeeper
scene-shop-intro-start = The shopkeeper looks up from her abacus as you come in.
scene-shop-intro-end = You leave with one apple, and the feeling you paid too much anyway.
scene-shop-buy = Buy something
scene-shop-buy-start = The shopkeeper holds something up and names a price.
scene-shop-buy-end = She wraps it in newspaper and drops the coins in a tin.

# What a reply does (action-<name>), and on a mix-up what was asked (asked-<name>).
# Concept values arrive as learner names: $item = "tea", $count = "three".
action-fetch = You bring { $item }.
asked-fetch = They wanted { $item }.
action-serve = You set down { $count } cups of { $item }.
asked-serve = They wanted { $count } cups of { $item }.
action-carry = You carry { $amount } { $item }s.
asked-carry = They wanted { $amount } { $item }s.
action-pick = You pick up the { $size } { $item }.
asked-pick = They wanted the { $size } { $item }.

# Conversations: what was asked, shown after a wrong reply. These are shared by every scene that
# uses the action, so they say "they" unless only one person ever uses it.
asked-hello = They were saying hello.
asked-greet = They were saying hello.
asked-wang = They were telling you their name.
asked-how = They wanted to know how you are.
asked-name = They were telling you what to call them.
asked-ask = They wanted your name.
asked-names = They told you their name and wanted yours.
asked-bye = They were saying goodbye.
asked-farewell = They were saying goodbye.
asked-answer = They said "{ $said }" and wanted the usual answer.
asked-hungry = They asked how you are, and your stomach has an answer.
asked-noodles = They were offering you noodles.
asked-like = They wanted to know if you like noodles.
asked-there = They were pointing somewhere.
asked-shop = They were telling you there's a restaurant over there.
asked-zhang = They said a name.
asked-friend = They were telling you about a friend.
asked-job = They were offering you work.
asked-live = They were telling you this room is yours.
asked-numbers = They wanted you to count along.
asked-next = They wanted the next number: { $number }.
asked-foreman = They were telling you their name.
asked-money = They wanted to know if you have money.
asked-rent = They were talking about the week's rent.
asked-price = They told you the price.
asked-dispatcher = They were telling you their name, and checking yours.
asked-places = They were showing you where things are.
asked-where = They wanted to know where the school is.
action-deliver = You'll take it to the { $place }.
asked-deliver = They wanted it taken to the { $place }.
asked-now = They wanted to know if you're going now.
asked-who = They wanted to know who you are.
asked-doctor = They were telling you they're a doctor.
asked-teacher = They were telling you they're a teacher.
asked-books = They wanted to know if it's books.
asked-beijing = They were telling you where they're going.
asked-time = They were telling you the time: { $hour } o'clock.
action-wash = You wash { $amount } cups.
asked-wash = They wanted { $amount } cups.
action-eat = You eat { $food }.
asked-eat = They were offering you { $food }.
asked-out = They were telling you they're out of cups.
asked-browse = They wanted to know what you're buying.
asked-fruit = They were showing you the fruit.
asked-apples = They were saying the apples are good.
asked-haggle = They told you the price: five kuai for one apple.
asked-less = They offered it for one kuai less.
action-buy = You pay { $price } kuai for the { $item }.
asked-buy = They wanted { $price } kuai for the { $item }.

# B3 slice 3
place-tea_house = Tea House
place-tea_house-desc = Low tables, a television in the corner, and an owner who pours tea from a great height.
place-stairs = Stairwell
place-stairs-desc = Bikes, shoes and a small dog. Your neighbour's door is always open.
npc-teaboss = Old Chen
npc-neighbour = Mrs Lin
npc-classmate = David
npc-driver = Old Ma
asked-meet = They said they're glad to meet you.
asked-tea = They were offering you tea.
asked-china = They wanted to know if you like China.
asked-work = They wanted to know what work you do.
asked-come = They wanted you to come and work on Saturday.
scene-tea-intro = Meet Old Chen
scene-tea-intro-start = A man with a long-spouted kettle waves you to a low table.
scene-tea-intro-end = Old Chen refills your cup without asking. Come back on Saturday, he seems to say, and bring your hands.
action-pour = You pour { $amount } cups of { $drink }.
asked-pour = They wanted { $amount } cups of { $drink }.
action-seat = You bring { $people } cups and { $people } chairs to the table.
asked-seat = They said { $people } people are at that table.
asked-busy = A customer was complaining there's not enough tea.
scene-tea-shift = Pour tea
scene-tea-shift-start = Every table is full. Old Chen hands you the kettle.
scene-tea-shift-end = The last table leaves. Old Chen counts out your pay.
asked-cold = They were saying it's cold today.
asked-weather = They wanted to know what you think of the weather.
asked-rain = They were saying it's raining again.
asked-hot = They were warning you the tea is hot.
asked-clock = They wanted to know what time it is.
asked-when = They wanted to know when you come to work.
asked-minutes = They were offering ten minutes' rest and a cup of tea.
scene-tea-weather = Talk about the weather
scene-tea-weather-start = Rain drums on the tin roof. Old Chen sits down across from you with a sigh.
scene-tea-weather-end = Old Chen shows you the clock on the wall and taps it twice. Time, and rain: two things worth talking about.
asked-tvon = They wanted the television on.
asked-tv = They wanted to know if you watch television.
asked-all = They were saying everyone watches.
asked-call = They were taking a phone call.
asked-sorry = Someone was apologising.
asked-see = They wanted to know if you saw the dog on the television.
asked-film = They wanted quiet for the film.
asked-nextvisit = They wanted to know when you're coming tomorrow.
scene-tea-tv = Watch TV
scene-tea-tv-start = The regulars want the television on. Old Chen pulls up a stool for you.
scene-tea-tv-end = Everybody groans at the ending. Old Chen switches the television off and the regulars go home.
asked-flat = They were telling you their flat number.
asked-years = They were telling you how long they've lived here.
asked-son = They were introducing their son.
asked-age = They were telling you how old their son is.
scene-stairs-meet = Meet the neighbour
scene-stairs-meet-start = A woman with a shopping bag and a small boy stops on the stairs to look at you.
scene-stairs-meet-end = Mrs Lin says something to her son, who waves at you shyly and runs upstairs.
asked-photo = They were showing you a family photo.
asked-people = They were saying how many people are in their family.
asked-parents = They were pointing out their father and mother.
asked-jobs = They were telling you what their parents do.
asked-daughter = They were introducing their daughter.
asked-pretty = They wanted to know if you think their daughter is pretty.
asked-clothes = They were talking about someone's clothes.
asked-love = They were saying their daughter loves cats.
scene-stairs-family = See the family photo
scene-stairs-family-start = Mrs Lin holds a framed photo out to you, proudly.
scene-stairs-family-end = Mrs Lin puts the photo back on the shelf by her door, and straightens it twice.
asked-dog = They were showing you their dog.
asked-loves = They were saying their son and husband love the dog.
asked-seen = They wanted to know if you've seen their cat.
asked-asleep = They were showing you the cat, asleep.
scene-stairs-pets = Meet the dog
scene-stairs-pets-start = A small dog comes bouncing down the stairs and straight into your legs, with Mrs Lin's son right behind it.
scene-stairs-pets-end = The dog decides you're all right and falls asleep on your foot.
asked-study = They wanted to know if you study Chinese.
asked-teacherintro = They were introducing themselves as the teacher.
asked-seat-class = They were offering you a chair.
asked-listen = They wanted you to listen.
asked-can = They wanted to know if you know Chinese.
asked-writechar = They wanted to know if you can write characters.
asked-mate = They were introducing a classmate.
asked-comeclass = They wanted to know if you can come to school.
asked-classday = They were telling you when the class is.
scene-class-first = Join the Chinese class
scene-class-first-start = The teacher from the gate beckons you in. There's an evening class for grown-ups, and a free desk.
scene-class-first-end = The teacher writes your name on the class list. Saturday afternoon, then.
asked-writeyear = They wanted you to write the year.
asked-day = They were telling you the date.
asked-book = They were showing you their book.
asked-writename = They wanted you to write your name.
asked-hush = They were warning you the teacher is coming.
scene-class-write = Write characters
scene-class-write-start = David shoves his notebook across the desk. The teacher wants the date at the top of the page, and he's stuck.
scene-class-write-end = The teacher collects the notebooks. David's page and yours look suspiciously alike.
asked-computer = They were saying they have a computer.
asked-parentsjob = They were saying what their parents do.
asked-pets = They were telling you about their pets.
asked-films = They wanted to know if you love films.
asked-compliment = They were admiring your clothes.
asked-snack = They were offering you fruit.
asked-backtowork = They were warning you the teacher is back.
scene-class-break = Talk with David
scene-class-break-start = The teacher steps out. David turns his chair round to face you.
scene-class-break-end = The teacher comes back, and David spins his chair round just in time.
asked-read = They wanted you to read the book.
asked-howread = They wanted to know how to read some characters.
asked-readaloud = They wanted you to read aloud while everyone listens.
asked-talk = They wanted to know who's talking at the back.
asked-good = They were praising your Chinese.
scene-class-read = Read aloud
scene-class-read-start = The teacher opens the book at the first page and looks straight at you.
scene-class-read-end = The teacher nods: good enough. David is still pretending he wasn't talking.
asked-taxi = They were calling out for passengers.
asked-whereto = They wanted to know where you're going.
asked-plane = They were joking that you'd need a plane.
asked-fare = They were thinking about a taxi to Beijing.
asked-toomuch = They said it would cost a lot.
asked-lady = They were asking if you're not going after all.
scene-taxi-way = Meet the taxi driver
scene-taxi-way-start = A taxi driver leans on his car outside the station, calling to everyone who walks past.
scene-taxi-way-end = Old Ma laughs and slaps the roof of his taxi. If you ever want work lifting bags, he knows where to find you.
action-load = You lift { $amount } bags { $way } the taxi.
asked-load = They wanted { $amount } bags { $way } the taxi.
action-train = You load the bags for the { $hour } o'clock train to Beijing.
asked-train = They wanted the bags for the { $hour } o'clock train to Beijing.
asked-busyphone = They were taking a call.
asked-paid = They were paying you.
scene-taxi-luggage = Carry luggage
scene-taxi-luggage-start = A train has just come in. Old Ma points at a pile of bags and then at you.
scene-taxi-luggage-end = The last bag is in. Old Ma pays you out of his cap.
asked-knowhim = They wanted to know if you know that man.
asked-arrived = They were telling you when he arrived.
asked-afternoon = They were correcting you: it was the afternoon.
asked-visit = They were telling you about his daughter.
asked-howgo = They wanted to know how he'll get to Beijing.
asked-date = They were telling you the date.
asked-year = They were saying the man is getting in the taxi.
scene-taxi-visitor = Meet a visitor
scene-taxi-visitor-start = Old Ma nods at a tired man with a suitcase who's reading the timetable.
scene-taxi-visitor-end = The visitor gets into the taxi, and Old Ma drives him away, honking twice as he goes.
asked-phone = They were checking who answered the phone.
asked-caller = They were saying who's calling, and asking if you were asleep.
asked-forecast = They were saying it'll rain tomorrow morning, and be cold.
asked-tomorrow = They were telling you tomorrow's date.
asked-closed = They were saying the shop won't open tomorrow.
asked-away = They were saying they're flying somewhere tomorrow.
asked-plans = They wanted to know what you're doing tomorrow.
scene-room-phone = Answer the phone
scene-room-phone-start = The phone on the wall rings. Nobody but Mr Li has this number.
scene-room-phone-end = Mr Li hangs up. You look out at the rain and decide to go to bed.
asked-sit = They wanted you to sit down.
asked-sick = They wanted to know what's wrong.
asked-dressed = They were saying you're not dressed warmly enough.
asked-since = They wanted to know since when.
asked-rest = They wanted to know if you can sleep.
asked-water = They were telling you to drink water.
asked-food = They were telling you to eat properly.
asked-screen = They were telling you to rest.
scene-hospital-checkup = See the doctor
scene-hospital-checkup-start = You've been sneezing since the rain. The doctor takes one look at you and points at a chair.
scene-hospital-checkup-end = The doctor writes something illegible, hands it to you, and waves you out. Rest, food and water.
asked-open = They were saying the restaurant is open.
asked-crowd = They were saying there are lots of people.
asked-rice = They were saying the rice is running low.
asked-spot = They were pointing out a customer.
asked-these = They wanted these dishes taken to a table.
asked-bill = A customer wanted to know the price.
asked-lunch = They were inviting you to eat.
asked-taste = They wanted to know how the food is.
scene-noodle-lunch = Help with the lunch rush
scene-noodle-lunch-start = It's noon and the restaurant is full to the door. The cook waves you behind the counter.
scene-noodle-lunch-end = The last customer leaves. The cook sits down with you and two bowls, and finally stops shouting.
