# The story. intro-1, intro-2, … open a new game ($currency, $wallet, $rent are available).
intro-1 = China, 1980. There is no phone in your pocket, no translator in your bag, and nobody on this street who speaks your language: whatever you have to say, you will say it in Chinese.
intro-2 = You have { $currency }{ $wallet }. There is a room for you down the street; the rent, { $currency }{ $rent }, falls due at the end of each week, and food costs money every day.
intro-3 = There is work in the noodle shop, at the warehouse, out on the road. It needs words, and words get you paid in full only when you get them right the first time.
intro-4 = On a bench by the road an old man is watching you with open curiosity. Maybe start there.

# Where and when, on the top bar.
setting-where = Suzhou, 1980
setting-type-prompt = Type it in Chinese or pinyin:

place-street = Main Street
place-street-desc = Bikes, steam, and an old man on a bench.
place-noodle_shop = Noodle Shop
place-noodle_shop-desc = Steam everywhere, and the cook shouting orders at nobody.
place-room = Your Room
place-room-desc = A narrow bed, a window on the street, and a landlord who hears every step.
place-market = Market Street
place-market-desc = Stalls, scooters, and a warehouse with its doors open.
place-station_road = Station Road
place-station_road-desc = A wide road down to the station, a tea house steaming on the corner.
place-school = School
place-school-desc = Children's voices through the open windows, and a teacher at the gate.
place-hospital = Hospital
place-hospital-desc = White walls, a long queue, and a doctor hurrying past.
place-station = Train Station
place-station-desc = Announcements you can't follow, people with too much luggage, and a taxi driver shouting for fares.
place-shop = Corner Shop
place-shop-desc = Shelves to the ceiling, a crate of apples by the door, and a shopkeeper who misses nothing.
place-warehouse = Warehouse
place-warehouse-desc = Stacks of tables and chairs, and a big man with a clipboard.

npc-wang = Old Wang
npc-cook = Xiao Zhang
npc-landlord = Mr Li
npc-foreman = Big Liu
npc-dispatcher = Miss Gao
npc-doctor = Doctor
npc-teacher = Teacher
npc-traveller = Traveller
npc-shopkeeper = Shopkeeper

# Scene names for the menu; scene-<id>-start and scene-<id>-end are optional narration.
scene-street-hello = Meet Old Wang
scene-street-hello-start = The old man pats the bench beside him. Stuck? Press [w] to look a word up.
scene-street-hello-end = Old Wang looks delighted, and repeats your name, getting it wrong each time.

scene-street-hungry = Talk about food
scene-street-hungry-start = Your stomach growls, and Old Wang raises an eyebrow.
scene-street-hungry-end = Old Wang points down the street at a noodle shop: his friend Xiao Zhang cooks there.

scene-street-practice = Practise greetings
scene-street-practice-start = Old Wang waves you back over: greet him, mind your manners, then say goodbye properly.
scene-street-practice-end = Old Wang beams, satisfied you've finally got your manners right.

scene-street-numbers = Count with Old Wang
scene-street-numbers-start = Old Wang holds up his fingers: time to learn to count.

scene-noodle-bowl = Get a bowl of noodles
scene-noodle-bowl-start = Steam rolls out of the door. The cook glances up from her pot and waves you to a stool.
scene-noodle-bowl-end = She waves your money away: Old Wang's friends eat free, once. Then she's back at the pot, shouting orders she has nobody to count out.
scene-noodle-intro = Ask about work
scene-noodle-intro-start = Xiao Zhang looks you up and down, wiping her hands: a customer, or a pair of hands?
scene-noodle-intro-end = She throws you an apron: you have a job.

scene-noodle-shift = Work a shift
scene-noodle-shift-start = Xiao Zhang shoves you toward the counter and starts shouting orders: fetch drinks, serve customers.
scene-noodle-shift-end = The last order goes out. Xiao Zhang wipes her hands and pays you.

scene-room-hello = Meet the landlord
scene-room-hello-start = A thin man in slippers opens the door before you knock.
scene-room-hello-end = Mr Li hands you a key on a red string: the room is yours.
scene-room-rent = Talk about rent
scene-room-rent-start = Mr Li waits at the top of the stairs, rubbing his fingers together.
scene-room-rent-end = Mr Li nods and writes fifty on his hand. It's due every week.

scene-warehouse-intro = Meet the foreman
scene-warehouse-intro-start = The big man with the clipboard raises an eyebrow: can you count?
scene-warehouse-intro-end = Big Liu writes something on his clipboard, possibly your name.

scene-warehouse-shift = Carry furniture
scene-warehouse-shift-start = Big Liu points at the furniture and calls out what to carry. Do what he says.
scene-warehouse-shift-end = Shift over. Big Liu counts the pieces and pays you.

scene-delivery-intro = Meet Miss Gao
scene-delivery-intro-start = A young woman at a stall piled with parcels waves you over.
scene-delivery-intro-end = Miss Gao writes your name on a parcel label, then holds the parcel out to you.
scene-delivery-pickup = Take a delivery
scene-delivery-pickup-start = Miss Gao slaps a parcel down: say where it's going, then get moving before she changes her mind.
scene-delivery-hospital = Deliver the parcel
scene-delivery-hospital-start = The doctor at the desk looks up: say who you're delivering for, then hand the parcel over.
scene-delivery-hospital-end = The doctor signs your slip. Delivery done.
scene-delivery-school = Deliver the parcel
scene-delivery-school-start = The teacher waiting by the gate holds out a hand: say who sent you, then the books.
scene-delivery-school-end = The teacher takes the books and signs your slip. Delivery done.
scene-delivery-station = Deliver the parcel
scene-delivery-station-start = The traveller checks his watch: say who you're looking for, and when the Beijing train leaves.
scene-delivery-station-end = He thanks you and hurries off. Delivery done.

scene-noodle-kitchen = Wash dishes
scene-noodle-kitchen-start = Xiao Zhang waves you to the sink: wash cups, grab a bite, then get back out front.
scene-noodle-kitchen-end = You dry your hands and head back out front.
scene-shop-intro = Meet the shopkeeper
scene-shop-intro-start = The shopkeeper looks up from her abacus as you come in.
scene-shop-intro-end = You leave with one apple, and the feeling you paid too much anyway.
scene-shop-buy = Buy something
scene-shop-buy-start = The shopkeeper eyes the shelves: name what you want, and the price, before she'll sell it.
scene-shop-buy-end = You count coins into her hand and step back out onto the street.

# What a reply does (action-<name>), and on a mix-up what was asked (asked-<name>).
# Concept values arrive as learner names: $item = "tea", $count = "three".
action-fetch = You bring { $item }.
asked-fetch = Xiao Zhang wanted { $item }.
action-serve = You set down { $count } cups of { $item }.
asked-serve = Xiao Zhang wanted { $count } cups of { $item }.
action-carry = You carry { $amount } { $item }s.
asked-carry = Big Liu wanted { $amount } { $item }s.
action-pick = You pick up the { $size } { $item }.
asked-pick = Big Liu wanted the { $size } { $item }.

# Conversations: what was asked, shown after a wrong reply. These are shared by every scene that
# uses the action, so they say "they" unless only one person ever uses it.
asked-hello = Old Wang said hello.
asked-greet = { $npc } said hello.
asked-wang = Old Wang told you his name.
asked-how = { $npc } asked how you are.
asked-name = { $npc } told you their name.
asked-ask = Old Wang wanted your name.
asked-names = { $npc } gave a name, and asked for yours.
asked-bye = { $npc } said goodbye.
asked-farewell = Old Wang said goodbye.
asked-answer = Old Wang said "{ $said }", wanting a reply.
asked-hungry = { $npc } wanted to know if you're hungry.
asked-noodles = { $npc } offered you noodles.
asked-like = { $npc } wanted to know if you like noodles.
asked-count = { $npc } wanted you to count the cups.
asked-there = Old Wang pointed down the street.
asked-shop = Old Wang pointed out a restaurant.
asked-friend = Old Wang said Xiao Zhang is his friend.
asked-oldfriend = { $npc } asked if Old Wang is your friend.
asked-job = { $npc } offered you work.
asked-live = Mr Li said the room is yours.
asked-numbers = { $npc } asked you to count along.
asked-next = Old Wang wanted the next number: { $number }.
asked-foreman = Big Liu told you his name.
asked-money = Mr Li wanted to know if you have money.
asked-rent = Mr Li talked about the week's rent.
asked-price = Mr Li told you the price.
asked-dispatcher = Miss Gao gave her name, and asked yours.
asked-places = Miss Gao showed you where things are.
asked-where = Miss Gao wanted to know where the school is.
action-deliver = You'll take it to the { $place }.
asked-deliver = Miss Gao wanted it taken to the { $place }.
asked-now = Miss Gao wanted to know if you're going now.
asked-who = { $npc } asked who you are.
asked-doctor = The doctor introduced the job: doctor.
asked-teacher = The teacher introduced the job: teacher.
asked-books = The teacher wanted to know if it's books.
asked-beijing = The traveller named the destination.
asked-time = The traveller told you the time: { $hour }.
action-wash = You wash { $amount } cups.
asked-wash = Xiao Zhang wanted { $amount } cups.
action-eat = You eat { $food }.
asked-eat = Xiao Zhang offered you { $food }.
asked-out = Xiao Zhang said she's out of cups.
asked-browse = The shopkeeper asked what you're buying.
asked-fruit = The shopkeeper showed you the fruit.
asked-apples = The shopkeeper said the apples are good.
asked-haggle = The shopkeeper named the price: five kuai.
asked-less = The shopkeeper offered it for one kuai less.
action-buy = You pay { $price } kuai for the { $item }.
asked-buy = Wanted { $price } kuai for the { $item }.

# B3 slice 3
place-tea_house = Tea House
place-tea_house-desc = Low tables, a television in the corner, and an owner who pours tea from a great height.
place-stairs = Stairwell
place-stairs-desc = Bikes, shoes, a small dog, and a neighbour's door always open.
npc-teaboss = Old Chen
npc-neighbour = Mrs Lin
npc-classmate = David
npc-driver = Old Ma
asked-meet = Old Chen said it's nice to meet you.
asked-tea = Old Chen offered you tea.
asked-china = Old Chen wanted to know if you like China.
asked-work = { $npc } asked about work.
asked-come = Old Chen wanted you working Saturday.
scene-tea-intro = Meet Old Chen
scene-tea-intro-start = A man with a long-spouted kettle waves you to a low table.
scene-tea-intro-end = Old Chen refills your cup without asking.
action-pour = You pour { $amount } cups of { $drink }.
asked-pour = Old Chen wanted { $amount } cups of { $drink }.
action-seat = You bring { $people } cups and { $people } chairs to the table.
asked-seat = Old Chen said { $people } are at the back table.
asked-busy = { $npc } wanted tea.
scene-tea-shift = Pour tea
scene-tea-shift-start = Old Chen ties on your apron and calls out orders: pour tea, seat guests, keep moving.
scene-tea-shift-end = The tea house empties out. Old Chen counts the cups and pays you.
asked-cold = Old Chen said it's cold today.
asked-weather = Old Chen asked what you think of the weather.
asked-rain = Old Chen said it's raining again.
asked-hot = Old Chen warned you the tea is hot.
asked-clock = Old Chen wanted to know what time it is.
asked-when = Old Chen asked when you come to work.
asked-minutes = Old Chen offered ten minutes' rest and tea.
scene-tea-weather = Talk about the weather
scene-tea-weather-start = Rain drums on the tin roof, and Old Chen sits down with a sigh.
scene-tea-weather-end = Old Chen shows you the clock on the wall and taps it twice.
asked-tvon = Old Chen wanted the television on.
asked-tv = Old Chen asked if you watch TV.
asked-all = Old Chen said everyone watches.
asked-call = Old Chen took a phone call.
asked-sorry = { $npc } apologised.
asked-see = Old Chen asked if you saw the dog on TV.
asked-film = Old Chen wanted quiet for the film.
asked-nextvisit = Old Chen asked when you're back tomorrow.
scene-tea-tv = Watch TV
scene-tea-tv-start = The regulars want the television on, and Old Chen pulls up a stool.
asked-flat = Mrs Lin told you her flat number.
asked-years = Mrs Lin said how long she's lived here.
asked-son = Mrs Lin introduced her son.
asked-age = Mrs Lin told you her son's age.
scene-stairs-meet = Meet the neighbour
scene-stairs-meet-start = A woman with a shopping bag and a small boy stops on the stairs to look at you.
scene-stairs-meet-end = Mrs Lin says something to her son, who waves at you shyly and runs upstairs.
asked-photo = Mrs Lin showed you a family photo.
asked-people = Mrs Lin named her family's size.
asked-parents = Mrs Lin pointed out her parents.
asked-jobs = Mrs Lin told you her parents' jobs.
asked-daughter = Mrs Lin introduced her daughter.
asked-pretty = Mrs Lin asked if her daughter is pretty.
asked-clothes = Mrs Lin talked about someone's clothes.
asked-love = Mrs Lin said her daughter loves cats.
scene-stairs-family = See the family photo
scene-stairs-family-start = Mrs Lin holds a framed photo out to you, proudly.
asked-dog = Mrs Lin showed you her dog.
asked-loves = Mrs Lin: son and husband love the dog.
asked-seen = Mrs Lin asked if you've seen her cat.
asked-asleep = Mrs Lin showed you the sleeping cat.
asked-offerfruit = Mrs Lin offered you fruit.
scene-stairs-pets = Meet the dog
scene-stairs-pets-start = A small dog bounces down the stairs into your legs, Mrs Lin's son behind it.
asked-study = The teacher asked if you study Chinese.
asked-teacherintro = The teacher introduced themselves to the class.
asked-seat-class = The teacher offered you a chair.
asked-listen = The teacher wanted you to listen.
asked-can = The teacher asked if you know Chinese.
asked-writechar = Teacher asked if you can write characters.
asked-mate = The teacher introduced a classmate.
asked-comeclass = The teacher asked if you can come to school.
asked-classday = The teacher said when the class is.
scene-class-first = Join the Chinese class
scene-class-first-start = The teacher from the gate beckons you into a class for grown-ups.
scene-class-first-end = The teacher writes your name on the class list.
asked-writeyear = David wanted you to write the year.
asked-day = David told you the date.
asked-book = David showed you his book.
asked-writename = David wanted you to write your name.
asked-hush = David warned you the teacher is coming.
scene-class-write = Write characters
scene-class-write-start = David shoves his notebook across the desk, stuck on the date on the board.
scene-class-write-end = The teacher collects the notebooks; David's page looks suspiciously like yours.
asked-computer = David said he has a computer.
asked-parentsjob = David said his parents' jobs.
asked-pets = David told you about his pets.
asked-films = David wanted to know if you love films.
asked-compliment = David admired your clothes.
asked-snack = David offered you fruit.
asked-backtowork = David warned you the teacher is back.
scene-class-break = Talk with David
scene-class-break-start = The teacher steps out, and David turns his chair to face you.
asked-read = The teacher wanted you to read the book.
asked-howread = Teacher asked how to read some characters.
asked-readaloud = Teacher wanted you reading aloud.
asked-talk = Teacher asked who's talking at the back.
asked-good = The teacher praised your Chinese.
scene-class-read = Read aloud
scene-class-read-start = The teacher opens the book at the first page and looks straight at you.
asked-taxi = Old Ma called out for passengers.
asked-whereto = Old Ma wanted to know where you're going.
asked-plane = Old Ma joked you'd need a plane.
asked-fare = Old Ma thought about a taxi to Beijing.
asked-toomuch = Old Ma said it would cost a lot.
asked-lady = Old Ma asked if you're not going after all.
scene-taxi-way = Meet the taxi driver
scene-taxi-way-start = A taxi driver leans on his car outside the station, calling to everyone who walks past.
action-load = You lift { $amount } things { $way } the taxi.
asked-load = Old Ma wanted { $amount } things in the taxi.
action-train = You load the bags for the { $hour } o'clock train to Beijing.
asked-train = Old Ma wanted bags for the { $hour } train.
asked-busyphone = Old Ma took a call.
asked-paid = Old Ma paid you.
scene-taxi-luggage = Carry luggage
scene-taxi-luggage-start = Old Ma waves you over: load the bags, check the train time, mind his ringing phone.
scene-taxi-luggage-end = The taxi pulls away. Old Ma taps the fare into your hand.
asked-knowhim = Old Ma wanted to know if you know that man.
asked-arrived = Old Ma told you when he arrived.
asked-afternoon = Old Ma said it was the afternoon.
asked-visit = Old Ma told you about his daughter.
asked-howgo = Old Ma wondered how he'll manage the luggage.
asked-newcomer = Old Ma said why he came to China.
asked-daughteryear = Old Ma said when his daughter came here.
asked-schoolday = Old Ma said when his daughter starts school.
asked-seeoff = Old Ma said the man is getting in the taxi.
scene-taxi-visitor = Meet a visitor
scene-taxi-visitor-start = Old Ma nods at a tired man with a suitcase who's reading the timetable.
asked-phone = Mr Li checked who answered the phone.
asked-caller = Mr Li named the caller, asked if you slept.
asked-forecast = Mr Li said it'll rain and be cold tomorrow.
asked-tomorrow = Mr Li told you tomorrow's date.
asked-closed = Mr Li said the shop won't open tomorrow.
asked-away = Mr Li said he's flying somewhere tomorrow.
asked-plans = Mr Li asked what you're doing tomorrow.
scene-room-phone = Answer the phone
scene-room-phone-start = The phone on the wall rings; only Mr Li has this number.
asked-sit = The doctor wanted you to sit down.
asked-sick = The doctor wanted to know what's wrong.
asked-dressed = The doctor said you're not dressed warmly.
asked-since = The doctor wanted to know since when.
asked-rest = The doctor wanted to know if you can sleep.
asked-water = The doctor told you to drink water.
asked-food = The doctor told you to eat properly.
asked-screen = The doctor told you to rest.
scene-hospital-checkup = See the doctor
scene-hospital-checkup-start = You've been sneezing, and the doctor points you to a chair.
scene-hospital-checkup-end = The doctor waves you out. Rest, food, and water.
asked-open = Xiao Zhang said the restaurant is open.
asked-crowd = Xiao Zhang said there are lots of people.
asked-rice = Xiao Zhang said the rice is running low.
asked-spot = Xiao Zhang pointed out a customer.
asked-these = Xiao Zhang wanted dishes taken to a table.
asked-bill = { $npc } wanted to know the price.
asked-lunch = Xiao Zhang invited you to eat.
asked-taste = Xiao Zhang wanted to know how the food is.
scene-noodle-lunch = Help with the lunch rush
scene-noodle-lunch-start = It's noon, and the cook waves you behind the counter.
scene-noodle-lunch-end = The last customer leaves, and the cook finally sits down with you.

# Notebook topics: a word in one of these slot groups is filed under the topic, not the place.
notebook-topic-foods = Food and drink
notebook-topic-drinks = Food and drink
notebook-topic-numbers_2_5 = Numbers
notebook-topic-numbers_3_5 = Numbers
notebook-topic-numbers_3_10 = Numbers
notebook-topic-courtesies = Courtesies
notebook-topic-furniture = Things
notebook-topic-goods = Things
notebook-topic-sizes = Sizes
notebook-topic-destinations = Places
notebook-topic-ways = Getting around
