# The story. intro-1, intro-2, … open a new game ($currency, $wallet, $rent are available).
intro-1 = China, 2004. Your bag is gone, passport and all. The police say: come back in a month.
intro-2 = You have { $currency }{ $wallet }, and nobody here speaks your language. Whatever you need, you will ask for in Chinese.
intro-3 = A room is down the street; rent { $currency }{ $rent } a week, and food costs money every day. Work pays in full only when you get the words right first time.
intro-4 = On a bench by the road an old man is watching you. Maybe start there.

place-street = Main Street
place-street-desc = Bikes, steam and an old man on a bench; your room is down past the noodle shop.
place-noodle_shop = Noodle Shop
place-noodle_shop-desc = Steam everywhere, and the cook shouting orders at nobody.
place-room = Your Room
place-room-desc = A narrow bed, a window on the street, and a landlord who hears every step.
place-market = Market Street
place-market-desc = Stalls, scooters, and a warehouse with its doors open.
place-station_road = Station Road
place-station_road-desc = A wide road down to the station, a tea house steaming on the corner.
place-school = School
place-school-desc = Children's voices through the open windows, and a teacher at the gate.
place-hospital = Hospital
place-hospital-desc = White walls, a long queue, and a doctor hurrying past.
place-station = Train Station
place-station-desc = Announcements you can't follow, people with too much luggage, and a taxi driver shouting for fares.
place-shop = Corner Shop
place-shop-desc = Shelves to the ceiling, a crate of apples by the door, and a shopkeeper who misses nothing.
place-warehouse = Warehouse
place-warehouse-desc = Stacks of tables and chairs, and a big man with a clipboard.

npc-wang = Old Wang
npc-cook = Xiao Zhang
npc-landlord = Mr Li
npc-foreman = Big Liu
npc-dispatcher = Miss Gao
npc-doctor = Doctor
npc-teacher = Teacher
npc-traveller = Traveller
npc-shopkeeper = Shopkeeper

# Scene names for the menu; scene-<id>-start and scene-<id>-end are optional narration.
scene-street-hello = Meet Old Wang
scene-street-hello-start = The old man pats the bench beside him. Stuck? Press [w] to look a word up.
scene-street-hello-end = Old Wang looks delighted, and repeats your name, getting it wrong each time.

scene-street-hungry = Talk about food
scene-street-hungry-start = Your stomach growls, and Old Wang raises an eyebrow.
scene-street-hungry-end = Old Wang points at the noodle shop, then at you.

scene-street-practice = Practise greetings

scene-street-numbers = Count with Old Wang
scene-street-numbers-start = Old Wang holds up his fingers: time to learn to count.

scene-noodle-intro = Ask about work
scene-noodle-intro-start = The cook looks you up and down, wiping her hands.
scene-noodle-intro-end = She throws you an apron: you have a job.

scene-noodle-shift = Work a shift

scene-room-hello = Meet the landlord
scene-room-hello-start = A thin man in slippers opens the door before you knock.
scene-room-hello-end = Mr Li hands you a key on a red string.
scene-room-rent = Talk about rent
scene-room-rent-start = Mr Li waits at the top of the stairs, rubbing his fingers together.
scene-room-rent-end = Mr Li nods and writes fifty on his hand. It's due every week.

scene-warehouse-intro = Meet the foreman
scene-warehouse-intro-start = The big man with the clipboard raises an eyebrow: can you count?
scene-warehouse-intro-end = Big Liu writes something on his clipboard, possibly your name.

scene-warehouse-shift = Carry furniture

scene-delivery-intro = Meet Miss Gao
scene-delivery-intro-start = A young woman at a stall piled with parcels waves you over.
scene-delivery-intro-end = Miss Gao writes your name on a parcel label, then holds the parcel out to you.
scene-delivery-pickup = Take a delivery
scene-delivery-hospital = Deliver the parcel
scene-delivery-school = Deliver the parcel
scene-delivery-station = Deliver the parcel

scene-noodle-kitchen = Wash dishes
scene-shop-intro = Meet the shopkeeper
scene-shop-intro-start = The shopkeeper looks up from her abacus as you come in.
scene-shop-intro-end = You leave with one apple, and the feeling you paid too much anyway.
scene-shop-buy = Buy something

# What a reply does (action-<name>), and on a mix-up what was asked (asked-<name>).
# Concept values arrive as learner names: $item = "tea", $count = "three".
action-fetch = You bring { $item }.
asked-fetch = Xiao Zhang wanted { $item }.
action-serve = You set down { $count } cups of { $item }.
asked-serve = Xiao Zhang wanted { $count } cups of { $item }.
action-carry = You carry { $amount } { $item }s.
asked-carry = Big Liu wanted { $amount } { $item }s.
action-pick = You pick up the { $size } { $item }.
asked-pick = Big Liu wanted the { $size } { $item }.

# Conversations: what was asked, shown after a wrong reply. These are shared by every scene that
# uses the action, so they say "they" unless only one person ever uses it.
asked-hello = Old Wang was saying hello.
asked-greet = { $npc } was saying hello.
asked-wang = Old Wang was telling you his name.
asked-how = { $npc } asked how you are.
asked-name = { $npc } told you their name.
asked-ask = Old Wang wanted your name.
asked-names = { $npc } gave a name, and asked for yours.
asked-bye = { $npc } was saying goodbye.
asked-farewell = Old Wang was saying goodbye.
asked-answer = Old Wang said "{ $said }", wanting a reply.
asked-hungry = Old Wang wanted to know if you're hungry.
asked-noodles = Old Wang was offering you noodles.
asked-like = { $npc } wanted to know if you like noodles.
asked-count = { $npc } wanted you to count the cups.
asked-there = Old Wang pointed down the street.
asked-shop = Old Wang was pointing out a restaurant.
asked-friend = Old Wang said Xiao Zhang is his friend.
asked-job = { $npc } offered you work.
asked-live = Mr Li was telling you this room is yours.
asked-numbers = { $npc } asked you to count along.
asked-next = Old Wang wanted the next number: { $number }.
asked-foreman = Big Liu was telling you his name.
asked-money = Mr Li wanted to know if you have money.
asked-rent = Mr Li was talking about the week's rent.
asked-price = Mr Li told you the price.
asked-dispatcher = Miss Gao gave her name, and asked yours.
asked-places = Miss Gao was showing you where things are.
asked-where = Miss Gao wanted to know where the school is.
action-deliver = You'll take it to the { $place }.
asked-deliver = Miss Gao wanted it taken to the { $place }.
asked-now = Miss Gao wanted to know if you're going now.
asked-who = { $npc } asked who you are.
asked-doctor = The doctor introduced the job: doctor.
asked-teacher = The teacher introduced the job: teacher.
asked-books = The teacher wanted to know if it's books.
asked-beijing = The traveller named the destination.
asked-time = The traveller told you the time: { $hour }.
action-wash = You wash { $amount } cups.
asked-wash = Xiao Zhang wanted { $amount } cups.
action-eat = You eat { $food }.
asked-eat = Xiao Zhang was offering you { $food }.
asked-out = Xiao Zhang said she's out of cups.
asked-browse = The shopkeeper asked what you're buying.
asked-fruit = The shopkeeper was showing you the fruit.
asked-apples = The shopkeeper said the apples are good.
asked-haggle = The shopkeeper named the price: five kuai.
asked-less = The shopkeeper offered it for one kuai less.
action-buy = You pay { $price } kuai for the { $item }.
asked-buy = Wanted { $price } kuai for the { $item }.

# B3 slice 3
place-tea_house = Tea House
place-tea_house-desc = Low tables, a television in the corner, and an owner who pours tea from a great height.
place-stairs = Stairwell
place-stairs-desc = Bikes, shoes, a small dog, and a neighbour's door always open.
npc-teaboss = Old Chen
npc-neighbour = Mrs Lin
npc-classmate = David
npc-driver = Old Ma
asked-meet = Old Chen said it's nice to meet you.
asked-tea = Old Chen was offering you tea.
asked-china = Old Chen wanted to know if you like China.
asked-work = { $npc } asked about work.
asked-come = Old Chen wanted you working Saturday.
scene-tea-intro = Meet Old Chen
scene-tea-intro-start = A man with a long-spouted kettle waves you to a low table.
scene-tea-intro-end = Old Chen refills your cup without asking.
action-pour = You pour { $amount } cups of { $drink }.
asked-pour = Old Chen wanted { $amount } cups of { $drink }.
action-seat = You bring { $people } cups and { $people } chairs to the table.
asked-seat = Old Chen said { $people } are at the back table.
asked-busy = { $npc } wanted tea.
scene-tea-shift = Pour tea
asked-cold = Old Chen was saying it's cold today.
asked-weather = Old Chen asked what you think of the weather.
asked-rain = Old Chen was saying it's raining again.
asked-hot = Old Chen was warning you the tea is hot.
asked-clock = Old Chen wanted to know what time it is.
asked-when = Old Chen asked when you come to work.
asked-minutes = Old Chen offered ten minutes' rest and tea.
scene-tea-weather = Talk about the weather
scene-tea-weather-start = Rain drums on the tin roof, and Old Chen sits down with a sigh.
scene-tea-weather-end = Old Chen shows you the clock on the wall and taps it twice.
asked-tvon = Old Chen wanted the television on.
asked-tv = Old Chen asked if you watch TV.
asked-all = Old Chen was saying everyone watches.
asked-call = Old Chen was taking a phone call.
asked-sorry = { $npc } was apologising.
asked-see = Old Chen asked if you saw the dog on TV.
asked-film = Old Chen wanted quiet for the film.
asked-nextvisit = Old Chen asked when you're back tomorrow.
scene-tea-tv = Watch TV
scene-tea-tv-start = The regulars want the television on, and Old Chen pulls up a stool.
asked-flat = Mrs Lin was telling you her flat number.
asked-years = Mrs Lin said how long she's lived here.
asked-son = Mrs Lin was introducing her son.
asked-age = Mrs Lin was telling you her son's age.
scene-stairs-meet = Meet the neighbour
scene-stairs-meet-start = A woman with a shopping bag and a small boy stops on the stairs to look at you.
scene-stairs-meet-end = Mrs Lin says something to her son, who waves at you shyly and runs upstairs.
asked-photo = Mrs Lin was showing you a family photo.
asked-people = Mrs Lin named her family's size.
asked-parents = Mrs Lin was pointing out her parents.
asked-jobs = Mrs Lin was telling you her parents' jobs.
asked-daughter = Mrs Lin was introducing her daughter.
asked-pretty = Mrs Lin asked if her daughter is pretty.
asked-clothes = Mrs Lin was talking about someone's clothes.
asked-love = Mrs Lin said her daughter loves cats.
scene-stairs-family = See the family photo
scene-stairs-family-start = Mrs Lin holds a framed photo out to you, proudly.
asked-dog = Mrs Lin was showing you her dog.
asked-loves = Mrs Lin: son and husband love the dog.
asked-seen = Mrs Lin asked if you've seen her cat.
asked-asleep = Mrs Lin was showing you the cat, asleep.
asked-offerfruit = Mrs Lin was offering you fruit.
scene-stairs-pets = Meet the dog
scene-stairs-pets-start = A small dog bounces down the stairs into your legs, Mrs Lin's son behind it.
asked-study = The teacher asked if you study Chinese.
asked-teacherintro = The teacher was introduced to the class.
asked-seat-class = The teacher was offering you a chair.
asked-listen = The teacher wanted you to listen.
asked-can = The teacher asked if you know Chinese.
asked-writechar = Teacher asked if you can write characters.
asked-mate = The teacher was introducing a classmate.
asked-comeclass = The teacher asked if you can come to school.
asked-classday = The teacher said when the class is.
scene-class-first = Join the Chinese class
scene-class-first-start = The teacher from the gate beckons you into a class for grown-ups.
scene-class-first-end = The teacher writes your name on the class list.
asked-writeyear = David wanted you to write the year.
asked-day = David was telling you the date.
asked-book = David was showing you his book.
asked-writename = David wanted you to write your name.
asked-hush = David was warning you the teacher is coming.
scene-class-write = Write characters
scene-class-write-start = David shoves his notebook across the desk, stuck on the date on the board.
scene-class-write-end = The teacher collects the notebooks; David's page looks suspiciously like yours.
asked-computer = David said he has a computer.
asked-parentsjob = David was saying his parents' jobs.
asked-pets = David was telling you about his pets.
asked-films = David wanted to know if you love films.
asked-compliment = David was admiring your clothes.
asked-snack = David was offering you fruit.
asked-backtowork = David was warning you the teacher is back.
scene-class-break = Talk with David
scene-class-break-start = The teacher steps out, and David turns his chair to face you.
asked-read = The teacher wanted you to read the book.
asked-howread = Teacher asked how to read some characters.
asked-readaloud = Teacher wanted you reading aloud.
asked-talk = Teacher asked who's talking at the back.
asked-good = The teacher was praising your Chinese.
scene-class-read = Read aloud
scene-class-read-start = The teacher opens the book at the first page and looks straight at you.
asked-taxi = Old Ma was calling out for passengers.
asked-whereto = Old Ma wanted to know where you're going.
asked-plane = Old Ma was joking that you'd need a plane.
asked-fare = Old Ma was thinking about a taxi to Beijing.
asked-toomuch = Old Ma said it would cost a lot.
asked-lady = Old Ma asked if you're not going after all.
scene-taxi-way = Meet the taxi driver
scene-taxi-way-start = A taxi driver leans on his car outside the station, calling to everyone who walks past.
action-load = You lift { $amount } things { $way } the taxi.
asked-load = Old Ma wanted { $amount } things in the taxi.
action-train = You load the bags for the { $hour } o'clock train to Beijing.
asked-train = Old Ma wanted bags for the { $hour } train.
asked-busyphone = Old Ma was taking a call.
asked-paid = Old Ma was paying you.
scene-taxi-luggage = Carry luggage
asked-knowhim = Old Ma wanted to know if you know that man.
asked-arrived = Old Ma was telling you when he arrived.
asked-afternoon = Old Ma said it was the afternoon.
asked-visit = Old Ma was telling you about his daughter.
asked-howgo = Old Ma wondered how he'll manage the luggage.
asked-newcomer = Old Ma was telling you why he came to China.
asked-daughteryear = Old Ma said when his daughter came here.
asked-schoolday = Old Ma said when his daughter starts school.
asked-seeoff = Old Ma said the man is getting in the taxi.
scene-taxi-visitor = Meet a visitor
scene-taxi-visitor-start = Old Ma nods at a tired man with a suitcase who's reading the timetable.
asked-phone = Mr Li was checking who answered the phone.
asked-caller = Mr Li named the caller, asked if you slept.
asked-forecast = Mr Li said it'll rain and be cold tomorrow.
asked-tomorrow = Mr Li was telling you tomorrow's date.
asked-closed = Mr Li said the shop won't open tomorrow.
asked-away = Mr Li said he's flying somewhere tomorrow.
asked-plans = Mr Li asked what you're doing tomorrow.
scene-room-phone = Answer the phone
scene-room-phone-start = The phone on the wall rings; only Mr Li has this number.
asked-sit = The doctor wanted you to sit down.
asked-sick = The doctor wanted to know what's wrong.
asked-dressed = The doctor said you're not dressed warmly.
asked-since = The doctor wanted to know since when.
asked-rest = The doctor wanted to know if you can sleep.
asked-water = The doctor was telling you to drink water.
asked-food = The doctor was telling you to eat properly.
asked-screen = The doctor was telling you to rest.
scene-hospital-checkup = See the doctor
scene-hospital-checkup-start = You've been sneezing, and the doctor points you to a chair.
scene-hospital-checkup-end = The doctor waves you out. Rest, food, and water.
asked-open = Xiao Zhang was saying the restaurant is open.
asked-crowd = Xiao Zhang said there are lots of people.
asked-rice = Xiao Zhang said the rice is running low.
asked-spot = Xiao Zhang was pointing out a customer.
asked-these = Xiao Zhang wanted dishes taken to a table.
asked-bill = { $npc } wanted to know the price.
asked-lunch = Xiao Zhang was inviting you to eat.
asked-taste = Xiao Zhang wanted to know how the food is.
scene-noodle-lunch = Help with the lunch rush
scene-noodle-lunch-start = It's noon, and the cook waves you behind the counter.
scene-noodle-lunch-end = The last customer leaves, and the cook finally sits down with you.
