# My own head. Complete sentence fragments; only $asked may be shortened.
voice-echo-1 = { $asked } I can use what I just heard.
voice-echo-2 = { $asked } The reply needn't start from nothing.
voice-echo-3 = { $asked } Some of the answer is already in the air.
voice-echo-4 = { $asked } I have something to work with.
voice-first-day-1 = Someone else's room, and my own head. At least one of them came with me.
voice-first-day-2 = The papers might know where I am. Worth asking the furniture.
voice-first-day-3 = { $currency }{ $wallet } in a stranger's wallet. I should find out whose.
voice-first-day-4 = Awake, apparently. Understanding can take its time.
voice-first-miss-1 = { $asked } { $word }{ $wordMeaning }.
voice-first-miss-2 = { $asked } At least { $word }{ $wordMeaning }.
voice-first-miss-3 = { $word }{ $wordMeaning }. { $asked }
voice-first-miss-4 = { $asked } One piece makes sense: { $word }{ $wordMeaning }.
voice-second-miss-1 = { $shape } { $memory }
voice-second-miss-2 = { $shape } One reply at a time.
voice-second-miss-3 = { $shape } That's enough for this moment.
voice-second-miss-4 = { $shape } I can try that much.
voice-stall-1 = { $asked } So { $word }{ $wordMeaning }.
voice-stall-2 = { $asked } I have one foothold: { $word }{ $wordMeaning }.
voice-stall-3 = { $word }{ $wordMeaning }; that much makes sense. { $asked }
voice-stall-4 = { $asked } Not all noise: { $word }{ $wordMeaning }.
voice-new-word-1 = { $word }{ $wordMeaning }. The Book can keep it for me.
voice-new-word-2 = { $word }{ $wordMeaning }. A little less noise.
voice-new-word-3 = { $word }{ $wordMeaning }. I may need that again.
voice-new-word-4 = { $word }{ $wordMeaning }. Something else with a name.
voice-scene-end-1 = { $reflection } Still on my feet.
voice-scene-end-2 = { $reflection } I'll take that much.
voice-scene-end-3 = { $reflection } Something to keep.
voice-scene-end-4 = { $reflection } A little less guessing.
voice-day-start-1 = { $situation } Another morning to work with.
voice-day-start-2 = { $situation } Day { $day }, then.
voice-day-start-3 = { $situation } I can start with breakfast.
voice-day-start-4 = { $situation } My head came along again.
voice-night-1 = { $situation } Sleep first.
voice-night-2 = { $currency }{ $wallet } left; { $known } words I trust. Neither feels like a fortune.
voice-night-3 = { $situation } A quiet ceiling would do.
voice-night-4 = { $situation } Enough guessing for one day.
voice-desk-wrong-1 = { $rule } The paper can wait.
voice-desk-wrong-2 = { $rule } One block at a time.
voice-desk-wrong-3 = { $rule } Less panic, perhaps.
voice-desk-wrong-4 = { $rule } It's still the same block.
voice-paper-done-1 = { $paper } One thing clearer.
voice-paper-done-2 = { $paper } Well, that explains something.
voice-paper-done-3 = { $paper } A clue, at least.
voice-paper-done-4 = { $paper } The paper knew all along.
voice-asked-fallback = I missed what was said.
voice-shape-intent = I need to { $intent }.
voice-shape-fallback = I need to answer what was asked.
voice-memory-used = I've made myself understood to { $npcShort } before.
voice-memory-new = One small reply will do.
voice-situation-hungry = My wallet won't cover a day's food.
voice-situation-rent = The rent is late, and it hasn't forgotten me.
voice-situation-march = Min-jun paid through March; my turn now, apparently.
voice-situation-room = Someone else's ID is still on the desk.
voice-situation-wallet = My wallet has { $currency }{ $wallet }, before food takes its share.
voice-reflection-first-earned = My first earnings here are finally in my pocket.
voice-reflection-lie = She believed my story about Min-jun.
voice-reflection-earned = I earned that money with my own mouth and hands.
voice-reflection-change = I couldn't make that change add up.
voice-reflection-landlady = She heard my answer; I have to live with it.
voice-reflection-desk = The newspaper word worked outside the room.
voice-reflection-march = A paid-up room, and a missing man.
voice-reflection-heard = I understood a little more of that voice.
voice-rule-silent = Initial ㅇ is silent; the vowel starts the sound.
voice-rule-final = First the initial, then the vowel, then the bottom consonant.
voice-rule-sum = The initial and vowel make one sound, in that order.
voice-paper-idcard = Kim Min-jun's name, not mine; this must be his room.
voice-paper-newspaper = A Seoul newspaper dated 2000; even the year isn't mine.
voice-paper-bill = A bill for 50,000 won, unpaid; apparently this room costs money.
# Korean-only chrome lives here to preserve the existing zh/ja learner text byte for byte.
keys-voice = [h] think · [?] meaning
keys-voice-type = [h] think when empty · [?] meaning
keys-voice-book = [b] book
keys-opening = [enter] continue · [ctrl-c] quit
keys-desk = Type the sound · [enter] read · [?] letters · [tab] book · [ctrl-c] quit
keys-desk-next = [enter] continue · [b] book · [ctrl-c] quit
keys-status = [esc] back
voice-status = [s] status
voice-help = Think it through [h]

voice-small-talk-1 = { $asked } A conversation I can stay in, apparently.
voice-small-talk-2 = { $asked } I can answer one thing at a time.
voice-small-talk-3 = { $asked } Nothing to sell or count for a moment.
voice-small-talk-4 = { $asked } Someone is talking to me between jobs.
voice-word-meaning = { " means " }{ $gloss }
voice-form-origin = { ", from " }{ $base }: { $gloss }
